### ISSUE TITLE
3D parts models are missing

### ISSUE THREAD

**Issue by adodon** [vmazmaz/MQTTCurtains#1]
Hi,
I love the project and will like to try myself to build a smart curtain. On the [Bill of materials](https://github.com/vmazmaz/MQTTCurtains/wiki/Bill-of-Materials#3d-printed-parts) you listed the 3D parts, did you had the occasion to upload them to Thingiverse ?

Do you continue to use the smart curtains how is the experience?

**Comment by vmazmaz** [comment]
Hi, 

I have to admit that I have not kept this wiki very much up to date ... I used the curtains for about 2 years (mostly) without problems. I would have liked to do more, in particular the calibration using the function form the TMC that senses when something is blocking the motor.
I don't think I will have time to post the files on thingiverse but I could upload the fusion360 file if you think it could be of interest to you.

**Comment by adodon** [comment]
Yes the fusion360 will be helpful. 
Thank you!

**Comment by vmazmaz** [comment]
Done, enjoy !

**Comment by adodon** [comment]
Thanks!
